package com.fubon.portal.repository;

import com.fubon.datasource.Auditable;

import io.swagger.v3.oas.annotations.media.Schema;
import java.util.Date;


public class Agent extends Auditable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MXACC.PORTAL_AGENT.SYS_ID
	 * @mbg.generated  Mon Jun 08 14:54:53 CST 2020
	 */
	@Schema(description = "系統代碼", required = true)
	private String sysId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MXACC.PORTAL_AGENT.USER_ID
	 * @mbg.generated  Mon Jun 08 14:54:53 CST 2020
	 */
	@Schema(description = "被代理人", required = true)
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MXACC.PORTAL_AGENT.AGENT_ID
	 * @mbg.generated  Mon Jun 08 14:54:53 CST 2020
	 */
	@Schema(description = "代理人", required = true)
	private String agentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MXACC.PORTAL_AGENT.START_TIME
	 * @mbg.generated  Mon Jun 08 14:54:53 CST 2020
	 */
	@Schema(description = "起始時間", required = true)
	private Date startTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MXACC.PORTAL_AGENT.END_TIME
	 * @mbg.generated  Mon Jun 08 14:54:53 CST 2020
	 */
	@Schema(description = "結束時間", required = true)
	private Date endTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MXACC.PORTAL_AGENT.SN
	 * @mbg.generated  Mon Jun 08 14:54:53 CST 2020
	 */
	private Short sn;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MXACC.PORTAL_AGENT.SYS_ID
	 * @return  the value of MXACC.PORTAL_AGENT.SYS_ID
	 * @mbg.generated  Mon Jun 08 14:54:53 CST 2020
	 */
	public String getSysId() {
		return sysId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MXACC.PORTAL_AGENT.SYS_ID
	 * @param sysId  the value for MXACC.PORTAL_AGENT.SYS_ID
	 * @mbg.generated  Mon Jun 08 14:54:53 CST 2020
	 */
	public void setSysId(String sysId) {
		this.sysId = sysId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MXACC.PORTAL_AGENT.USER_ID
	 * @return  the value of MXACC.PORTAL_AGENT.USER_ID
	 * @mbg.generated  Mon Jun 08 14:54:53 CST 2020
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MXACC.PORTAL_AGENT.USER_ID
	 * @param userId  the value for MXACC.PORTAL_AGENT.USER_ID
	 * @mbg.generated  Mon Jun 08 14:54:53 CST 2020
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MXACC.PORTAL_AGENT.AGENT_ID
	 * @return  the value of MXACC.PORTAL_AGENT.AGENT_ID
	 * @mbg.generated  Mon Jun 08 14:54:53 CST 2020
	 */
	public String getAgentId() {
		return agentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MXACC.PORTAL_AGENT.AGENT_ID
	 * @param agentId  the value for MXACC.PORTAL_AGENT.AGENT_ID
	 * @mbg.generated  Mon Jun 08 14:54:53 CST 2020
	 */
	public void setAgentId(String agentId) {
		this.agentId = agentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MXACC.PORTAL_AGENT.START_TIME
	 * @return  the value of MXACC.PORTAL_AGENT.START_TIME
	 * @mbg.generated  Mon Jun 08 14:54:53 CST 2020
	 */
	public Date getStartTime() {
		return startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MXACC.PORTAL_AGENT.START_TIME
	 * @param startTime  the value for MXACC.PORTAL_AGENT.START_TIME
	 * @mbg.generated  Mon Jun 08 14:54:53 CST 2020
	 */
	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MXACC.PORTAL_AGENT.END_TIME
	 * @return  the value of MXACC.PORTAL_AGENT.END_TIME
	 * @mbg.generated  Mon Jun 08 14:54:53 CST 2020
	 */
	public Date getEndTime() {
		return endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MXACC.PORTAL_AGENT.END_TIME
	 * @param endTime  the value for MXACC.PORTAL_AGENT.END_TIME
	 * @mbg.generated  Mon Jun 08 14:54:53 CST 2020
	 */
	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MXACC.PORTAL_AGENT.SN
	 * @return  the value of MXACC.PORTAL_AGENT.SN
	 * @mbg.generated  Mon Jun 08 14:54:53 CST 2020
	 */
	public Short getSn() {
		return sn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MXACC.PORTAL_AGENT.SN
	 * @param sn  the value for MXACC.PORTAL_AGENT.SN
	 * @mbg.generated  Mon Jun 08 14:54:53 CST 2020
	 */
	public void setSn(Short sn) {
		this.sn = sn;
	}

	private String userName;

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}
	
	private String sysName;

	public String getSysName() {
		return sysName;
	}

	public void setSysName(String sysName) {
		this.sysName = sysName;
	}
	
	
}