package com.fubon.portal.repository;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

@Repository
public interface AgentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MXACC.PORTAL_AGENT
	 * @mbg.generated  Mon Jun 08 14:54:53 CST 2020
	 */
	int insert(Agent record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MXACC.PORTAL_AGENT
	 * @mbg.generated  Mon Jun 08 14:54:53 CST 2020
	 */
	List<Agent> selectAll();

	List<Agent> findAgent (@Param("agentId")String agentId, @Param("checkDate")String checkDate);
	
}