package com.fubon.portal.repository;

import com.github.pagehelper.Page;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface AnnounceInfoMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MXACC.PORTAL_ANNOUNCE
	 * @mbg.generated  Mon Jun 08 14:54:53 CST 2020
	 */
	int insert(AnnounceInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MXACC.PORTAL_ANNOUNCE
	 * @mbg.generated  Mon Jun 08 14:54:53 CST 2020
	 */
	List<AnnounceInfo> selectAll();

	Page<AnnounceInfo> findAnnounceInfoList(@Param("showExpired")boolean showExpired, @Param("checkDate")String checkDate);
}