package com.fubon.portal.repository;

import com.fubon.datasource.Auditable;

public class MyFavoriteMenu extends Auditable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MXACC.PORTAL_MENU_MY_FAVORITE.USER_ID
	 * @mbg.generated  Mon Jun 08 14:54:53 CST 2020
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MXACC.PORTAL_MENU_MY_FAVORITE.ITEM_ID
	 * @mbg.generated  Mon Jun 08 14:54:53 CST 2020
	 */
	private Long itemId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MXACC.PORTAL_MENU_MY_FAVORITE.ALIAS_NAME
	 * @mbg.generated  Mon Jun 08 14:54:53 CST 2020
	 */
	private String aliasName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MXACC.PORTAL_MENU_MY_FAVORITE.DESCRIPTION
	 * @mbg.generated  Mon Jun 08 14:54:53 CST 2020
	 */
	private String description;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MXACC.PORTAL_MENU_MY_FAVORITE.USER_ID
	 * @return  the value of MXACC.PORTAL_MENU_MY_FAVORITE.USER_ID
	 * @mbg.generated  Mon Jun 08 14:54:53 CST 2020
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MXACC.PORTAL_MENU_MY_FAVORITE.USER_ID
	 * @param userId  the value for MXACC.PORTAL_MENU_MY_FAVORITE.USER_ID
	 * @mbg.generated  Mon Jun 08 14:54:53 CST 2020
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MXACC.PORTAL_MENU_MY_FAVORITE.ITEM_ID
	 * @return  the value of MXACC.PORTAL_MENU_MY_FAVORITE.ITEM_ID
	 * @mbg.generated  Mon Jun 08 14:54:53 CST 2020
	 */
	public Long getItemId() {
		return itemId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MXACC.PORTAL_MENU_MY_FAVORITE.ITEM_ID
	 * @param itemId  the value for MXACC.PORTAL_MENU_MY_FAVORITE.ITEM_ID
	 * @mbg.generated  Mon Jun 08 14:54:53 CST 2020
	 */
	public void setItemId(Long itemId) {
		this.itemId = itemId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MXACC.PORTAL_MENU_MY_FAVORITE.ALIAS_NAME
	 * @return  the value of MXACC.PORTAL_MENU_MY_FAVORITE.ALIAS_NAME
	 * @mbg.generated  Mon Jun 08 14:54:53 CST 2020
	 */
	public String getAliasName() {
		return aliasName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MXACC.PORTAL_MENU_MY_FAVORITE.ALIAS_NAME
	 * @param aliasName  the value for MXACC.PORTAL_MENU_MY_FAVORITE.ALIAS_NAME
	 * @mbg.generated  Mon Jun 08 14:54:53 CST 2020
	 */
	public void setAliasName(String aliasName) {
		this.aliasName = aliasName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MXACC.PORTAL_MENU_MY_FAVORITE.DESCRIPTION
	 * @return  the value of MXACC.PORTAL_MENU_MY_FAVORITE.DESCRIPTION
	 * @mbg.generated  Mon Jun 08 14:54:53 CST 2020
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MXACC.PORTAL_MENU_MY_FAVORITE.DESCRIPTION
	 * @param description  the value for MXACC.PORTAL_MENU_MY_FAVORITE.DESCRIPTION
	 * @mbg.generated  Mon Jun 08 14:54:53 CST 2020
	 */
	public void setDescription(String description) {
		this.description = description;
	}
}