package com.fubon.portal.repository;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MyFavoriteMenuMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MXACC.PORTAL_MENU_MY_FAVORITE
	 * @mbg.generated  Mon Jun 08 14:54:53 CST 2020
	 */
	int deleteByPrimaryKey(@Param("userId") String userId, @Param("itemId") Long itemId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MXACC.PORTAL_MENU_MY_FAVORITE
	 * @mbg.generated  Mon Jun 08 14:54:53 CST 2020
	 */
	int insert(MyFavoriteMenu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MXACC.PORTAL_MENU_MY_FAVORITE
	 * @mbg.generated  Mon Jun 08 14:54:53 CST 2020
	 */
	MyFavoriteMenu selectByPrimaryKey(@Param("userId") String userId, @Param("itemId") Long itemId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MXACC.PORTAL_MENU_MY_FAVORITE
	 * @mbg.generated  Mon Jun 08 14:54:53 CST 2020
	 */
	List<MyFavoriteMenu> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MXACC.PORTAL_MENU_MY_FAVORITE
	 * @mbg.generated  Mon Jun 08 14:54:53 CST 2020
	 */
	int updateByPrimaryKey(MyFavoriteMenu record);
}